# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: b57dec14-e535-4758-9af6-8ed4ade0e4cd-md-tks
  namespace: b57dec14-e535-4758-9af6-8ed4ade0e4cd
spec:
  clusterName: b57dec14-e535-4758-9af6-8ed4ade0e4cd
  replicas: 1
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        servicemesh: enabled
        taco-egress-gateway: enabled
        taco-ingress-gateway: enabled
        taco-lma: enabled
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: b57dec14-e535-4758-9af6-8ed4ade0e4cd-md-tks
      clusterName: b57dec14-e535-4758-9af6-8ed4ade0e4cd
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ByoMachineTemplate
        name: b57dec14-e535-4758-9af6-8ed4ade0e4cd-md-tks
      version: v1.22.3
