# Source: cluster-autoscaler/templates/rbac-for-mgmt-cluster-access.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-management
  namespace: b57dec14-e535-4758-9af6-8ed4ade0e4cd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-autoscaler-management
subjects:
- kind: ServiceAccount
  name: cluster-autoscaler
  namespace: b57dec14-e535-4758-9af6-8ed4ade0e4cd

